# Reference this view as ecomm__products
schema: ECOMM
table_name: PRODUCTS

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  cost:
    sql: '"COST"'

  category:
    sql: '"CATEGORY"'

  name:
    sql: '"NAME"'

  brand:
    sql: '"BRAND"'

  retail_price:
    sql: '"RETAIL_PRICE"'

  department:
    sql: '"DEPARTMENT"'

  sku:
    sql: '"SKU"'

  distribution_center_id:
    sql: '"DISTRIBUTION_CENTER_ID"'
    format: ID

measures:
  count:
    aggregate_type: count
