# Reference this view as demo__product_images
schema: DEMO
table_name: PRODUCT_IMAGES

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  image:
    sql: '"IMAGE"'

measures:
  count:
    aggregate_type: count
