# Reference this view as omni_dbt__product
schema_label: ""

schema: omni_dbt
table_name: PRODUCT

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  name:
    sql: '"NAME"'

  family:
    sql: '"FAMILY"'

  created_date:
    sql: '"CREATED_DATE"'

  product_code:
    sql: '"PRODUCT_CODE"'

measures:
  count:
    aggregate_type: count
